# ########################################################
# Set file '.mise.local.toml' in root project directory.

# [env]
# MY_SET_CLOUD_BENDER = "gcp"
# MY_GCP_PROFILE_NAME = "test-project"
# MY_GCP_ACCOUNT_NAME = "my-user@gcp.org.melanmeg.com"
# MY_GCP_PROJECT_ID   = "test-project-373118"
# MY_GCP_REGION       = "asia-northeast1"
# MY_GCP_ZONE         = "asia-northeast1-a"
# SCRIPT_DIR          = "~/.my/switch_cloud"

# [hooks.enter]
# shell = "bash"
# script = "source ~/.my/switch_cloud/switch.sh"

# [[watch_files]]
# patterns = [".mise.toml", ".tool-versions"]
# run = "mise i -y"

# [[watch_files]]
# patterns = ["package.json"]
# run = "npm i -y"
# ##########################################################

[env]
NODE_ENV = 'development'
NPM_CONFIG_PREFIX = '~/.npm-global'

[tools]
1password      = 'latest'
awscli         = 'latest'
azure-cli      = 'latest'
argocd         = 'latest'
bat            = 'latest'
bottom         = 'latest'
bun            = 'latest'
cloudflared    = 'latest'
crane          = 'latest'
delta          = 'latest'
deno           = 'latest'
duf            = 'latest'
dust           = 'latest'
fd             = 'latest'
# ffmpeg is used with containers.
# ffmpeg         = 'latest' # dependencies: nasm yasm gcc
gcloud         = 'latest'
helm           = 'latest'
helmfile       = 'latest'
hyperfine      = 'latest'
infracost      = 'latest'
java           = ['17.0.2']
jq             = 'latest'
k9s            = 'latest'
ksops          = 'latest'
kubectl        = 'latest'
mc             = 'latest'
minikube       = 'latest'
node           = ['20.15.1'] # 'lts'
packer         = 'latest'
# perl           = ['5.40.0']
pnpm           = 'latest'
poetry         = 'latest'
pre-commit     = 'latest'
python         = ['3.10.11', '3.11.9', '3.12.4']
ripgrep        = 'latest'
terraform      = ['1.9.2']
terraform-docs = 'latest'
tflint         = 'latest'
tfsec          = 'latest'
tfupdate       = 'latest'
trivy          = 'latest'
vals           = 'latest'
vault          = 'latest'
vhs            = 'latest'
yarn           = 'latest'
yq             = 'latest'
zoxide         = 'latest'

[plugins]

[settings]
legacy_version_file = true
legacy_version_file_disable_tools = ['terraform']  # parse-legacy-fileがrequired_versionパラメータのパースができなくてエラーとなるため回避
always_keep_download = false
always_keep_install = false
plugin_autoupdate_last_check_duration = '0'
trusted_config_paths = ['~']
verbose = false
asdf_compat = false
http_timeout = '30'
jobs = 4
raw = false
yes = true
not_found_auto_install = true
task_output = "prefix"
paranoid = false
disable_default_shorthands = false
env_file = '.env.mise'
experimental = true
status = { missing_tools = "if_other_versions_installed", show_env = false, show_tools = false }
