[env]
NODE_ENV = 'development'
NPM_CONFIG_PREFIX = '~/.npm-global'

[tools]
awscli         = 'latest'
azure-cli      = 'latest'
argocd         = 'latest'
bat            = 'latest'
bottom         = 'latest'
bun            = 'latest'
crane          = 'latest'
delta          = 'latest'
deno           = 'latest'
duf            = 'latest'
dust           = 'latest'
fd             = 'latest'
# ffmpeg is used with containers.
# ffmpeg         = 'latest' # dependencies: nasm yasm gcc
gcloud         = 'latest'
helm           = 'latest'
helmfile       = 'latest'
hyperfine      = 'latest'
infracost      = 'latest'
java           = ['17.0.2']
jq             = 'latest'
k9s            = 'latest'
ksops          = 'latest'
kubectl        = 'latest'
minikube       = 'latest'
node           = ['20.15.1'] # 'lts'
# perl           = ['5.40.0']
poetry         = 'latest'
pre-commit     = 'latest'
python         = ['3.10.11', '3.11.9', '3.12.4']
ripgrep        = 'latest'
sops           = 'latest'
terraform      = ['1.9.2']
terraform-docs = 'latest'
tflint         = 'latest'
tfsec          = 'latest'
tfupdate       = 'latest'
trivy          = 'latest'
vals           = 'latest'
vault          = 'latest'
vhs            = 'latest'
zoxide         = 'latest'

[plugins]

[settings]
legacy_version_file = true
legacy_version_file_disable_tools = ['']
always_keep_download = false
always_keep_install = false
plugin_autoupdate_last_check_duration = '0'
trusted_config_paths = ['~']
verbose = false
asdf_compat = false
http_timeout = '30'
jobs = 4
raw = false
yes = true
not_found_auto_install = true
task_output = "prefix"
paranoid = false
disable_default_shorthands = false
disable_tools = ['']
env_file = '.env.mise'
experimental = true
status = { missing_tools = "if_other_versions_installed", show_env = false, show_tools = false }
